In [1]:
import numpy as np
import pandas as pd

In [2]:
ventas = pd.read_csv('./Data/volumen_ventas_producto_sucursal.csv')

In [3]:
precios = pd.read_csv('./Data/precio_producto.csv')

In [4]:
precios

producto  Precio
0         Malbec     208
1       Cabernet     216
2          Syrah     247
3  Caberne Franc     180
4         Merlot     180
5     Pinot noir     243

In [5]:
ventas

producto  Sucursal 1  Sucursal 2  Sucursal 3  Sucursal 4  Sucursal 5  \
0         Malbec         429         106         437         177         200   
1       Cabernet         244         111         282         238         144   
2          Syrah         374         278         241         408         177   
3  Caberne Franc         449         291         461         484         452   
4         Merlot         222         494         436         252         161   
5     Pinot noir         335         137         233         487         394   

   Sucursal 6  Sucursal 7  
0         412         309  
1         198         331  
2         381         237  
3         388         466  
4         187         337  
5         488         331

In [6]:
sucurales = ventas.columns[1:8]

In [7]:
sucurales.values

array(['Sucursal 1', 'Sucursal 2', 'Sucursal 3', 'Sucursal 4',
       'Sucursal 5', 'Sucursal 6', 'Sucursal 7'], dtype=object)

In [8]:
ventasSuc = ventas.values[:,1:]
ventasSuc2 = ventas.iloc[:, 1:].values

In [9]:
ventasSuc
ventasSuc2
maxVenta = np.sum(ventasSuc, axis=0)

In [10]:

ventasSuc2

array([[429, 106, 437, 177, 200, 412, 309],
       [244, 111, 282, 238, 144, 198, 331],
       [374, 278, 241, 408, 177, 381, 237],
       [449, 291, 461, 484, 452, 388, 466],
       [222, 494, 436, 252, 161, 187, 337],
       [335, 137, 233, 487, 394, 488, 331]])

In [11]:
ventasSuc

array([[429, 106, 437, 177, 200, 412, 309],
       [244, 111, 282, 238, 144, 198, 331],
       [374, 278, 241, 408, 177, 381, 237],
       [449, 291, 461, 484, 452, 388, 466],
       [222, 494, 436, 252, 161, 187, 337],
       [335, 137, 233, 487, 394, 488, 331]], dtype=object)

In [12]:
maxVentaSuc= np.around(ventasSuc2.sum(axis=0), decimals=2)

In [13]:
maxVentaProd = np.around(ventasSuc2.sum(axis=1), decimals=2)

In [14]:
maxVentaSucID = np.around(maxVentaSuc.argmax(axis=0), decimals=2)

In [15]:
maxVentaPrdID = np.around(maxVentaProd.argmax(axis=0), decimals=2)

In [16]:
maxVentaSucID

2

In [17]:
maxVentaSuc


array([2053, 1417, 2090, 2046, 1528, 2054, 2011])

In [18]:
maxVentaPrdID

3

In [19]:
###############33sucursal que mas vendio 
sucurales[maxVentaSucID]

'Sucursal 3'

In [20]:
preciosUnitarios = precios.iloc[:,1:]

In [21]:

np.array(preciosUnitarios)

array([[208],
       [216],
       [247],
       [180],
       [180],
       [243]])

In [22]:
np.array(ventasSuc2)[::]

array([[429, 106, 437, 177, 200, 412, 309],
       [244, 111, 282, 238, 144, 198, 331],
       [374, 278, 241, 408, 177, 381, 237],
       [449, 291, 461, 484, 452, 388, 466],
       [222, 494, 436, 252, 161, 187, 337],
       [335, 137, 233, 487, 394, 488, 331]])

In [24]:
def getPrecio(i):
    return preciosUnitarios.values[i]

getPrecio(1)

array([216])

In [62]:

idx=0
def quePasa(i):
    print(i*getPrecio(1)[0])
    print (precioIdx)
    print (i)
    
    print ('-------------')
    

enumerate(ventasSuc2)

In [64]:
idx=1
np.array([quePasa(i ) for   i in (ventasSuc2)])


[92664 22896 94392 38232 43200 88992 66744]
0
[429 106 437 177 200 412 309]
-------------
[52704 23976 60912 51408 31104 42768 71496]
0
[244 111 282 238 144 198 331]
-------------
[80784 60048 52056 88128 38232 82296 51192]
0
[374 278 241 408 177 381 237]
-------------
[ 96984  62856  99576 104544  97632  83808 100656]
0
[449 291 461 484 452 388 466]
-------------
[ 47952 106704  94176  54432  34776  40392  72792]
0
[222 494 436 252 161 187 337]
-------------
[ 72360  29592  50328 105192  85104 105408  71496]
0
[335 137 233 487 394 488 331]
-------------


array([None, None, None, None, None, None], dtype=object)